### ISSUE TITLE
Argument with with hyphen and underscore shows up as true

### ISSUE THREAD

**Issue by styfle** [lukeed/mri#11]
## Steps to reproduce 

```js
const mri = require("mri")
const args = ["hello", "-foo_bar"]
const argv = mri(args)
console.log(argv._)
```

## Actual

```json
["hello", true]
```

## Expected

```json
["hello", "-foo_bar"]
```

**Comment by lukeed** [comment]
Hey,

It _definitely_ shouldn't be:

```
["hello", "-foo_bar"]
```

If anything, it should be:

```
["hello"]
```

...since the single flag expands all chars to `true` values. That said, I have to look up how `_` is supposed to be handled...

Makes more sense when you look at full parsed output:

```js
// Current

mri(['hello', '-foobar']);
//=> { _: [ 'hello' ],
//=>  f: true,
//=>  o: [ true, true ],
//=>  b: true,
//=>  a: true,
//=>  r: true }

mri(['hello', '-foo_bar']);
//=> { _: [ 'hello', true ],
//=>  f: true,
//=>  o: [ true, true ],
//=>  b: true,
//=>  a: true,
//=>  r: true }
```

It becomes `['hello', true]` because `_` here is seen as a short flag, much in the same way that the double `o` is being handled.

**Comment by styfle** [comment]
I see, I might be mistaken then. 

How would I capture an argument that should accept any string including hyphens and underscores?

**Comment by lukeed** [comment]
Not 100% sure what you're asking tbh, but I'll run through some examples to cover all the bases just in case I hit it :P

```js

**Comment by styfle** [comment]
Thanks for the quick and thorough response!

It seems the issue is my usage and not `mri`. I can see that `arg` also assumes this is a flag as well.

I'll close this issue, thanks!
